title: Pim Huijnen
description: Personal website
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name   : ""
  avatar : "/images/bio_photo.jpg"
  bio    : "Digital cultural historian"
  location: "Utrecht, NL"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pimhuijnen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pimhuijnen/recent-activity/all/"
    - label: "UU Staff"
      icon: "fas fa-fw fa-university"
      url: "https://www.uu.nl/staff/PHuijnen"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5477-6352"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=Pe4aDh4AAAAJ&hl=en"

minimal_mistakes_skin: "contrast"
locale: "en"
markdown: kramdown
highlighter: rouge
paginate: 5

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor"]

header_pages:
  - _pages/posts.md
  - _pages/research.md
  - _pages/publications.md
  - _pages/presentations.md
  - _pages/teaching.md
  - _pages/about.md
