title: Pim Huijnen
description: >- 
  Historian, teacher, researcher
url: "https://pimhuijnen.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

author:
  name   : "Pim Huijnen"
  avatar : "/assets/images/profile.png"
  bio    : "Historian, teacher, researcher"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

theme: minimal-mistakes-jekyll

collections:
  pages:
    output: true
    permalink: /:name/
