title: Pim Huijnen
description: Personal website
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name   : "Pim Huijnen"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Historian, researcher, digital humanities enthusiast."

minimal_mistakes_skin: "dark"
locale: "en"
markdown: kramdown
highlighter: rouge
paginate: 5

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor"]
