title: Pim Huijnen
email: your-email@example.com
description: >- 
  Historian, teacher, researcher, and writer.
baseurl: ""
url: "https://pimhuijnen.github.io"
theme: jekyll-theme-chirpy
lang: en
timezone: Europe/Amsterdam

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

collections:
  tabs:
    output: true
    permalink: /:collection/:name
