## Neue Wörter pro Jahr im Bundestag (1950-2021)


### 1950:
herren
damen
antrag
worden
abg
wort
spd
nr
deutschen
ausschuss
heute
frage
schon
herrn
müssen
ja
gesetz
zuruf
mehr
drucksache
möchte
darf
sagen
regierung
beifall
bundesregierung
richtig
darauf
millionen
kommen


### 1951:
luetkens
kemritz
montanunion
feiertage
investitionshilfe
kroupa
wahlorgan
hohenfels
bundesjugendplans
ago
gatt
kreyssig
umdrucke
heimatauskunftstellen
mindestrenten
arbeitsdirektor
abstimmungsbezirke
sowjetzonalen
xxvi
wohnungseigentümer
grenzschutzbehörden
sondereigentum
odenthal
schweizerischen
bundesgrenzschutz
einheitsgesellschaften
staatsgeheimnis
grenzschutzpolizei
dienstposten
übergangsgehälter


### 1952:
entschuld
fu
zusatzfrage
gesamtbetriebsrat
evg
knechtsand
generalvertrages
einigungsstelle
molkerei
gesamtbetriebsrats
vorbehaltsrechte
gema
branntweinwirtschaft
deutschlandvertrag
notstandsklausel
viermächteverhandlungen
wehrgewalt
generalkriegsvertrag
verteidigungsvertrag
geheimorganisation
behördenhandel
schwarzarbeiter
mulert
personalvertretungsgesetz
knechtsandes
sektkellereien
nationalarmee
knechtsands
vob
betriebsobmann


### 1953:
hilfsstimme
präferenz
bundesbank
oeftering
meincke
mehrheitswahlrechts
schuldenabkommens
anthony
angenfort
braumalz
bundessozialgerichts
handelsvertreters
umstellungsergänzungsgesetz
streitsache
graphischen
handschumacher
altbanken
kultivierungseinrede
steuerverwaltungskosten
buchführungspflicht
notenbanksystem
ausgleichsanspruches
rückvergütungen
vries
handelssaatgut
bundeslisten
landessozialgerichte
siedlungsbewerber
überschussgütern
mietrichtsätze


### 1954:
zonenrandgebiet
zonenrandgebiete
zonenrandgebieten
kindergeldgesetz
familienminister
ergänzungsabgabe
verkehrsfinanzgesetz
rasner
bender
niederalt
kindergeldes
verkehrsfinanzgesetzes
strassenentlastungsgesetz
hellwig
kindergeldanpassungsgesetz
rinke
cillien
stingl
wegekosten
finanzanpassungsgesetz
altrenten
volkszensur
johns
leiske
condor
vockenhausen
jentzsch
löhr
kindergeldgesetzes
seiboth


### 1955:
freiwilligengesetz
bundesverteidigungsminister
personalgutachterausschuss
kostenvergleichsmiete
soldatengesetz
schmeisser
bundesmietengesetz
luftfahrtindustrie
bundeswehr
kulturbesitz
carte
blanche
personalgutachterausschusses
personalkonzession
paritätsgesetze
radioaktiven
ziebell
sicherheitsausschusses
radioaktivität
zwangsschlichtung
sonderzulagen
reichskonkordats
soldatengesetzes
bundesverteidigungsministerium
atomkrieges
wiedergutmachungsausschuss
atomaren
personalversammlungen
mineralölgesellschaften
massenvernichtungswaffen


### 1956:
zenker
fvp
juliusturm
eurofima
studentenbundes
grundwehrdienstes
berufsheer
studentenbund
bergmannsprämie
grundentwurf
häftlingshilfegesetz
euratom
wehrbeauftragten
hirschmann
gewerbesteuersenkung
kernbrennstoffe
längerdienenden
verteidigungsdienstpflicht
jugendarchivs
überbrückungszahlung
kernbrennstoffen
atomkommission
grossadmiral
totverwertung
landbeschaffungsgesetzes
rheinseitenkanals
lohmar
vilshofen
warenautomaten
accord


### 1957:
anl
atomgesetzes
bergmannsrente
ausfallzeiten
iller
lohnwertrente
volksaktie
kriegsfolgengesetz
wehrstrafgesetz
rabattkartell
ausbauplan
sueskrise
seemannsgesetz
arreststrafe
saarklausel
versuchsexplosionen
rentenbemessungsgrundlage
hemsath
kommunalklausel
kriegsfolgengesetzes
trakehner
vergütungsfähig
wrasmann
wehrstrafgesetzes
heizölnovelle
krankenversicherungsreform
julitz
wissenschaftsrat
malzindustrie
rentnerbrief


### 1958:
barzel
sozialbericht
scherpenberg
ewg
harm
atomwaffenfreien
zoglmann
stoltenberg
kreitmeyer
atomwaffenfreie
burgbacher
logemann
claussen
crossman
bading
winterbau
mischnick
memmel
eilers
aigner
mosbach
rutschke
matadore
rapacki
görgen
reith
frede
weimer
dröscher
scharnowski


### 1959:
heizölsteuer
kohlenzoll
deutschlandplan
singularzulassung
kilb
unterbach
konzentrationsvorgänge
einfuhrverträge
anwaltserfordernis
rüstungsbegrenzungszone
berichtigungsaktien
energiemarkt
spork
sozialbonus
klemmert
kohlezoll
flehinghaus
murr
starfighter
prosperitätsklausel
münemann
eisele
landwirtschaftszählung
zechenanlagen
urteilsschelte
anwaltszwanges
abzweigstecker
stilwandel
kapitalberichtigung
güde


### 1960:
efta
baulandsteuer
entwicklungspolitik
guinea
carstens
weltflüchtlingsjahr
deutschlandfunk
gemeindepfennig
bebauungsplanes
bebauungsplan
eichmann
auslandsfunk
kontrastprogramm
vorsorgehilfe
beschleunigungsplan
konkurrenzprogramm
veränderungssperre
unternehmerfreibetrag
notdienstgesetz
theil
reiseandenken
spannungsfall
imle
reichsbankanteile
rollmann
kontaktausschuss
reichsnotarordnung
vorsorgeuntersuchungen
apothekenbetriebsordnung
beratungsärztlichen


### 1961:
kennedy
kindergeldkasse
allparteienregierung
nachbarortslinienverkehr
margentarife
bundesärzteordnung
karenztag
leihbüchereien
tarifkommissionen
zuweisungsverfahren
einrichtungshilfe
kriegswaffenkontrollgesetz
regellohns
fernsehurteil
johnson
touristikunternehmen
anhörverfahren
margentarifen
zweitkindergeldes
altersgelder
finanzamtlösung
dego
ungestempelte
koalitionsausschuss
gewährleistungsfrist
truppendienstrichter
verfassungskonform
währungsaufwertung
faktorenrente
betriebsprüfungsordnung


### 1962:
ahlers
hüttebräuker
harmonisierungsnovelle
ausbildungsförderung
warentests
empfehlungsschreiben
abmahnung
peiter
eurocontrol
rationalisierungsverband
flitz
abschöpfungssätze
bundesgesundheitsministerium
liehr
kaumann
rahmenzusagen
glombig
abschöpfungssätzen
tapiokamehl
marktorganisation
toyka
dickopf
aussenwirtschaftsverordnung
weihnachtsgänse
vh
wellmann
betonleitplanken
bögler
sozialpaketes
freyh


### 1963:
argoud
filbinger
wohnbeihilfengesetz
wohnbeihilfe
eisbrecher
amtsbl
bornemann
jugendzahnpflege
waldkirch
mietrechtlicher
schuldstrafrecht
neureut
warentestinstitut
eröffnendem
raumordnungsbericht
herstellungsdatums
begründungszwang
flämig
grossrohre
staatshandelsländern
wissenschaftsminister
resozialisierung
ernährungssicherstellungsgesetz
bremervörde
soldatenheime
planifikation
nordbrücke
pumpgemeinschaft
grenzausgleich
györfi


### 1964:
gumbel
grundsatzrevision
nagold
moersch
bildungsnotstand
mlf
zweierunion
fernschreibüberwachung
mikat
bildungsgefälle
kollbach
bruchreis
silberstein
vorwärtsverteidigung
grossheppach
teststoppabkommens
sozialinvestitionen
festlandsockel
upjever
vortragsreisen
postabgabe
energieversorgungsträger
jugendbegegnung
zebrastreifen
nichtzulassungsbeschwerde
schütte
härtenovelle
presserechtsrahmengesetz
pfullendorf
schiffahrtspolitik


### 1965:
haushaltssicherungsgesetz
osswald
ausbildungszulage
ausbildungszulagen
hüttenknappschaftlichen
formierten
wissenschaftsplan
haushaltssicherungsgesetzes
pressefunk
nievenheim
gdl
tarifvertragsfähigkeit
prüfungsrechte
marktstrukturfonds
realschulreife
bürohauses
landstuhl
kürzungsprogramm
finanzanarchie
march
rambouillet
kinderstationen
hüttenknappschaftliche
alleinvertretungsanspruch
vertrauensentzug
agrarfinanzierung
preissteigerungsrate
fusionsvertrag
marqués
zerbe


### 1966:
stabilitätsgesetz
friedensnote
raffert
apel
finanzplanungsgesetz
stabilisierungsgesetz
friderichs
zeitungsaustausch
kreditplafondierung
stabilitätsgesetzes
finanzvorausschau
konzertierten
berufsforschung
wörner
staratzke
häfele
nichtnuklearen
abelein
springorum
röhner
milchpolitik
klarstand
inflationsrate
schmidhuber
orgass
haehser
finanzplanungsgesetzes
verstromungsgesetz
stabilisierungsgesetzes
kilometerpauschale


### 1967:
schöllhorn
finanzänderungsgesetz
finanzänderungsgesetzes
symmetrie
kreditfinanzierungsgesetz
ankaufspreises
atomsperrvertrag
zielprojektion
arbeitsförderungsgesetz
stoph
kreditfinanzierungsgesetzes
airbus
investitionsprämie
schah
arbeitsförderungsgesetzes
flankierenden
abhörgeräte
eskalation
brennbuch
rentnerkrankenversicherungsbeitrag
flankierende
wohnungszählungsgesetz
talfahrt
kanzlerzusagen
seilbahnen
trainingszentren
barerstattungen
nichtverbreitungsvertrages
altvorräteentlastung
schwefliger


### 1968:
diehl
sonderziehungsrechte
aufklärungslücke
ruhnau
arbeitssicherstellungsgesetz
establishment
trennscheibe
pausch
flugsicherungsbeamten
nettokreditaufnahme
arbeitssicherstellungsgesetzes
finanzplanungsrates
steuerfront
abwrackaktion
sonderangebot
baltes
gemeinschaftsprogrammes
toxoplasmose
hausach
nkf
küffner
flottillenadmiral
zehnerklubs
haushaltsgrundsätzegesetz
abschlussgebühr
gesamtschule
familienbericht
trennwandverordnung
drittelparität
doping


### 1969:
riedl
nichteheliche
fusionskontrolle
niegel
esters
berufsbildungsgesetz
vorbeugungshaft
nichtaufwertung
aktionsprogramme
sozialtherapeutische
dasch
sozialtherapeutischen
lebach
vorbeugehaft
führungsaufsicht
bruttolohnfortzahlung
bussmann
berufsbildungsgesetzes
sportrat
dattendorfer
hochschulbauförderungsgesetzes
susset
projektgruppe
gerichtshilfe
hubmann
pick
sieglerschmidt
grashey
maassen
beurkundungswesen


### 1970:
umweltschutz
griesau
umweltschutzes
konjunktursperre
strukturbericht
gallus
konjunkturzuschlag
steffen
bildungsanleihe
barm
aufwertungsausgleich
krall
klasen
coreth
urbaniak
birckholtz
förderungsschwelle
storck
entführern
tatsachenbeschreibung
informationssperre
zielschwelle
aufwertungsausgleichs
schnellbaumassnahmen
konjunkturzuschlags
jusos
gemeindeverkehrsfinanzierungsgesetz
konjunktursperren
altersjahrgangs
rechtskorrekturamnestie


### 1971:
farthmann
gesundheitsbericht
umweltprogramm
ostverträge
vergleichsmiete
floaten
mützelburg
dreckmann
graduiertenförderungsgesetz
umweltprogramms
arzneimittelsicherheit
vring
halbzeitbilanz
falin
intensivprogramm
sprecherausschüsse
kse
versorgungsausgleich
apl
abteilungsversammlungen
gmd
hemfler
stagflation
chilenen
bewertungsänderungsgesetz
versorgungsausgleichs
verstärkungsprogramm
gottschalch
davis
aufwendungsdarlehen


### 1972:
erkel
cma
machens
mandel
verplombung
aussensteuergesetz
haftrechtsnovelle
verfügungsbereitschaft
waffenbesitzkarte
rönn
streikunterstützungen
disler
cantzler
haarnetze
zuverdienst
entlastungsgesetz
haftrechtes
wanderungsausgleich
inlandsaufklärung
mediengefahren
dienstgerechtigkeit
eintragungsgrenze
ersatzdienstrechtlicher
wehrrechtlicher
langwaffen
hartnack
verplombungsgesetz
carillo
menth
anästhesisten


### 1973:
lambsdorff
stabilitätsabgabe
ennepetal
gerster
gansel
grundlagenvertrag
zeitel
ey
möllemann
nordlohne
schoeler
glotz
conradi
pfeffermann
schuchardt
waigel
vohrer
todenhöfer
waffenschmidt
hölscher
grundlagenvertrages
grundvertrags
thürk
hornhues
benedix
abtreibungen
tillmann
stavenhagen
verhülsdonk
emstek


### 1974:
guillaume
bölling
verfassungsdebatte
grützmann
erziehungsgeld
markierungspunkten
energieforschungsprogramm
hillermeier
ausbildereignungsverordnung
minderpreisverträge
lernort
einkommensteuerreformgesetz
energiekonferenz
heichert
zollbereich
zwangsernährung
verhandlungspflicht
richtgeschwindigkeiten
laermann
aktenordnung
ölländer
auszahlungsanordnung
richtgeschwindigkeit
drenkmann
einstellungsbehörde
bürgerbeteiligung
waschmittelgesetz
guillaumes
töns
balling


### 1975:
haushaltsstrukturgesetz
sondergeneralversammlung
wyhl
weltrezession
ktk
haushaltsstrukturgesetzes
schleifenbaum
ausreiseprotokoll
lomé
rentenabkommen
krankenhausapotheken
gesundheitsabkommen
dreieckskooperation
studentenbereichs
pstsekr
partnerrente
wohnungsmodernisierung
heysing
trauerbeflaggung
berlinförderung
erlösstabilisierung
grimming
beschäftigungshilfen
röhlig
adoptionsvermittlungsstellen
wohnbesitzmodell
müntefering
familienberichts
kapverdischen
bissau


### 1976:
rico
zeittakt
vdj
gartenschläger
beschäftigungssystem
kampfunterstützungstruppen
kreibaum
mettke
patentstelle
meeresbodenbehörde
nahverkehrsbereichen
landwirtschaftsklausel
sperrguthabenvereinbarung
malawi
zwangsadoptionen
versicherungslösung
einzelzulassung
zusagenregelung
ausbildungsplatzförderungsgesetz
vorkaufsrechte
blockpartei
westfeld
jamaika
onkologie
aufstiegshilfe
krebshilfe
transferaufträge
elchlepp
kautionsregelung
gtz


### 1977:
steger
hasinger
riesenhuber
spöri
massenbach
daweke
cronenberg
langner
kühbacher
stutzer
rühe
gattermann
höpfinger
würzbach
kittelmann
gerstein
luster
hüsch
thüsing
regenspurger
konjunkturabschlag
broll
prangenberg
ludewig
diederich
wisniewski
angermeyer
kostendämpfungsgesetz
wartenberg
hoffacker


### 1978:
nico
realsplitting
mängelbericht
solaranlagen
erftstadt
rheumabekämpfung
verdachtskontrollen
tugendhat
heizenergie
bevorratungskosten
strafverfahrensänderungsgesetz
alternativempfehlungen
forschungsstation
asylsachen
wohnumfeldverbesserung
silberland
dkfz
konsultativrunde
pacepa
koordinierungsstab
energieeinsparenden
erdatmosphäre
rollbretter
transparenzliste
scheeler
formenkreises
angebotsorientierten
entgeltsteigerung
fliesen
generica


### 1979:
harrisburg
regelanfrage
monierbau
tschessiounias
holocaust
zumpfort
krebskonferenz
czempiel
routineanfrage
unverjährbar
widerspruchslösung
chemikaliengesetz
kinderbetreuungskosten
jablonski
kinderbetreuungsbetrag
einwilligungslösung
verjährungsentscheidung
sonderablieferung
mindestverbüssungsdauer
vietnamflüchtlinge
wimbledon
schneekatastrophe
angebotsschule
granzow
mutterschaftsurlaubsgesetz
völkerstrafrechtlichen
sinamos
bum
verjährungsunterbrechung
guadeloupe


### 1980:
afghanistans
franghi
kindergrundfreibetrag
betäubungsmittelrechts
sommerspielen
wechselschichtdienst
fremdkommerzialisierung
leistungsbilanzdefizits
weissenhofsiedlung
lärmvorsorge
menschenrechtserziehung
superabgabe
weserstadion
billigtarif
olympiaboykott
rechtsentscheids
schönhöfer
menschenrechtsorganisationen
afeb
scheinasylanten
meldegeheimnis
frequenzmodulation
esa
lauschoperationen
seriennummern
stiegler
stahlforschungsprogramm
therapieplätzen
golfregion
eritreer


### 1981:
kansy
dallmeyer
weirich
herberholz
catenhusen
repnik
bugl
subventionsabbaugesetz
lammert
dressler
hinsken
nichtregierungsorganisationen
linsmeier
bohl
lowack
gilges
rossmanith
fellner
roitzsch
herkenrath
dörflinger
weyel
sielaff
bredehorn
magin
jagoda
bernrath
weinhofer
poss
heistermann


### 1982:
haushaltsbegleitgesetzes
beschäftigungsförderungsgesetz
haushaltsbegleitgesetz
kleingartenanlagen
stocksolide
beschäftigungsförderungsgesetzes
beschäftigungshaushalt
burda
austermann
walesa
kleingewerbeförderung
benecke
flessner
conventional
bauherrenmodellen
pkk
zusatztaschengeld
wegharken
werkvertragsarbeitnehmer
volldarlehen
herbstkontrolle
unifil
jahrhundertvertrag
fares
polenkrise
insolvenzrücklage
sbk
mobiliarsicherheiten
teilhauptfeststellungsgesetz
staffelmietvereinbarung


### 1983:
reents
stratmann
burgmann
kelly
schwenninger
feilcke
krizsan
reetz
potthast
hoss
schoppe
jannsen
altun
dans
horacek
göhner
carstensen
drabiniok
verheyen
bard
meeresschildkröten
grünbeck
hornung
kemal
frauenhäuser
hauchler
uldall
odendahl
toetemeyer
rönsch


### 1984:
milchrente
ferlemann
abouchar
bkb
bhopal
kassetten
volkszählungsurteil
milchkontingentierung
pseudokrupp
dempwolf
schadstoffarmen
praxisphase
manöverbehinderungen
abgasarmen
gefahrstoffverordnung
kollegiaten
kvae
tempolimits
videofilme
einert
haftsummenzuschlag
technikfolgenabschätzung
amr
steuerbereinigungsgesetz
wieskirche
götzer
fremdreinigung
maschinenlesbare
haftungszuschlag
binnenorientierung


### 1985:
ströbele
schierholz
senfft
bueb
eureka
tatge
hönes
borgmann
rusche
gerlingen
süssmuth
dierstorf
auhagen
tiedge
pöppl
ranker
erziehungsurlaub
gorbatschow
hellenbroich
teltschik
hydrazin
fangunion
erziehungsgeldgesetz
sobernheimer
auswahlgespräch
hamburgneustadt
kabinettberichterstattung
bioethanol
technologiegemeinschaft
waldschadensbericht


### 1986:
tschernobyl
lappas
becquerel
berners
umwelttag
schleppnetzfahndung
marktentlastungsprogramm
braunmühl
reaktorkatastrophe
este
kuhbier
gorbatschows
neutralitätsausschuss
kröninger
halifax
auszubildendenvertretung
viehof
amöneburg
parkkralle
umweltausschusses
kirchholz
frauenministerin
umwelttages
streitkräfteziel
strommasten
dioxan
meisterprüfungsverordnung
strahlenschutzvorsorgegesetz
steuerbescheinigungsverfahren
jugendbegegnungsstätte


### 1987:
sellin
lippelt
vennegerts
wollny
flinner
saibold
götte
ebermann
irmer
wüppesahl
weiermann
hillerich
teubner
scherrer
wiefelspütz
hüser
diller
bulmahn
niehuis
hämmerle
uelhoff
ganseforth
seidenthal
grossmann
zumkley
leidinger
ritterhude
koltzsch
olms
harries


### 1988:
dehp
gesundheitsreformgesetz
depfa
produktionsaufgaberente
strukturhilfegesetz
montankonferenz
quellensteueramt
heydemann
referenzstrecke
grg
bst
festbetragsregelung
dara
vanunu
noriega
flugschauen
giftgaseinsätze
altersteilzeit
rahmendienstzeit
umflaggen
festbetragsmodell
aussiedlerinnen
regierungsbefragung
revierausgleich
flugtagen
rohstoffaktivitäten
atomskandal
ressourcenaktivitäten
montanrunde
wildsterben


### 1989:
rabta
meneses
vogl
friess
wittmoldt
bankenmacht
kastner
imhausen
vereinsförderungsgesetz
ökosteuer
danesh
schätzle
giftgasfabrik
bauschadensbericht
rushdie
terminbörse
eingliederungsgeld
kinderkommission
sicherheitskultur
spiesen
technikberatung
naturschutzabgabe
orthoptistinnen
demokratiebewegung
atomabschreckung
mordauftrag
escherde
dvu
meisner
wurfsendung


### 1990:
pds
einigungsvertrag
treuhandanstalt
umweltunion
einigungsvertrages
diestel
umweltrahmengesetz
wahlvertrag
wismut
dewitz
bürgerbewegungen
dsu
thierse
csfr
vereinigungsprozess
tropenwaldschutz
massaua
steinitz
enkelmann
romberg
dörfler
heltzig
arbeitnehmerhaftung
widerstandskoalition
stolfa
bitterfeld
wollenberger
haschke
roske
einigungsvertrags


### 1991:
larcher
albowitz
kriedner
bläss
titze
koppelin
schwanhold
lederer
koschyk
ilja
bonese
hoyerswerda
kozloduj
konstanze
schalck
kampeter
solidaritätszuschlag
altersübergangsgeld
iwersen
gleicke
altbundesländern
habermann
pofalla
knaape
seibel
mosdorf
mascher
gibtner
personalstärkegesetz
raidel


### 1992:
gus
dsd
vermögensrechtsänderungsgesetz
schnittler
bürgerkriegsflüchtlinge
riegert
ringkamp
premnitz
sikora
margarethenhütte
fujimori
alcor
risikostrukturausgleich
zinsabschlag
scharfenstein
altschuldenfrage
godewind
gerechtigkeitslücke
vermögensrechtsänderungsgesetzes
kriegsfolgenbereinigungsgesetz
dkk
sissy
südumfahrung
standortsicherungsgesetz
grossdubrau
gewinnaufspürungsgesetz
schönburgglauchau
probestudium
cetiner
bürgerkriegsflüchtlingen


### 1993:
bischofferode
belet
uen
entgeltfortzahlungsgesetz
fkp
iwc
unosom
drittstaatenregelung
standortbericht
blutprodukten
solidarpaktverhandlungen
kleinwale
föj
boutros
grams
niedenthal
fledermäuse
fallahian
tuzla
dwa
ahmadis
skwpg
energiekonsensgespräche
geldwäschegesetz
krebsmaus
asienkonzept
entgeltfortzahlungsgesetzes
messlösung
fraktionsgesetz
tlg


### 1994:
wto
tauss
medizinprodukte
korfu
parr
schirinowski
familienleistungsausgleich
glasbläser
alpenkonvention
szwed
magnetschwebebahnplanungsgesetz
srü
dressen
grundstoffüberwachungsgesetz
christos
thorp
neutronenquelle
schlitzwand
medizinprodukten
zukunftsministerium
minschen
jakubeit
technologierates
ugilec
hüüt
fünfliterauto
rückholaktion
partnerschaftsgesellschaft
notimpfung
deit


### 1995:
mochovce
höfken
raethjen
mietenüberleitungsgesetz
hovermann
labsch
temelin
universaldienst
brent
antipersonenminen
aktionsplattform
regulierungsbehörde
bohunice
pyrethroiden
monistik
bundesumweltministerin
telekommunikationsgesetz
jingsheng
reflexionsgruppe
nestmann
aufwertungsfestigkeit
einsatzverbandes
stadtbank
grosny
heyer
welajati
fischler
zwischenerwerber
kowaljow
zukunftsministers


### 1996:
postfilialen
afrg
schoene
hirntod
göllner
heiderich
gestaltungsleistungen
vernetzungsstelle
upahl
hsp
cwü
transplantationsmedizin
hirnfunktionen
ostwerften
stimmausweis
ifa
wohngeldüberleitungsgesetz
tkg
filialkonzept
privatagenten
hirnfunktion
flächenerwerbsverordnung
michendorf
teichmüller
bezügefortzahlung
techint
wipianer
sfor
eigentumsfristengesetz
scientologen


### 1997:
umweltplan
grundakte
immunitätenprotokoll
mikrotesla
iukdg
bürsch
nachhaltigkeitsstrategie
unternehmensübernahmen
übernahmekodex
erwerbsminderungsrente
wehrmachtsausstellung
dolly
demenzkranken
effizienzrendite
sangershausen
hormonell
beschäftigungsgipfels
goll
sportsicherung
verbrauchsteuerabteilung
kofi
amateurfunkgesetz
oderregion
rehaeinrichtungen
blockadevorwurf
betreuungsrechts
gsa
signaturgesetz
sarkuhi
kontrag


### 1998:
stollmann
pallas
loske
sylvia
vieheinheitenstaffel
kenzler
divag
kzbv
siemann
evelyn
gebhardt
lötzer
aribert
vosshoff
deligöz
ekin
brase
folta
brandner
edathy
investitionsabkommen
lietz
helias
bodewig
girisch
krampkarrenbauer
humme
romanes
gehb
dött


### 1999:
tampere
eisenman
hartnagel
kosovaren
interfet
roos
kandidatenstatus
jump
tokaimura
haushaltssanierungsgesetzes
zeitarbeitsfirmen
mifegyne
einbürgerungszusicherung
generationenbilanz
stelenfeld
warndatei
stiftungskultur
schuldeninitiative
suchlauf
postunterstützungskassen
drogenkonsumräumen
westtimor
beratungsresistent
pudlv
erziehungsbedarf
kfor
stiftungsrechtsreform
winterbauausschüsse
eisenmans
abzinsungsgebot


### 2000:
vonseiten
card
agrardiesel
potenzial
feira
potenziale
scheinselbstständigkeit
stammzellen
bettin
grietje
aufseiten
steuersenkungsergänzungsgesetz
potenziellen
rating
kostunica
substanzielle
trockenbau
agrardieselgesetz
griese
kelber
potenzielle
lebenspartnerschaftsgesetz
generationenbilanzen
elternzeit
ostseekooperation
haackes
agrardiesels
weltstaatsmann
sebnitz
gnauck


### 2001:
agrarwende
laeken
schartau
onlinewahlen
wohnortprinzips
geoinformationen
massstäbegesetzes
nordallianz
talibanregime
uranmunition
aussengastronomie
euroumstellung
greencard
stadtumbauprogramm
religionsprivilegs
verbraucherschutzministerin
stammzellenforschung
gleichstellungsdurchsetzungsgesetz
hittfeld
osama
geodaten
gewaltschutzgesetzes
fallpauschalensystems
antiterrorkoalition
chrobog
adulten
versorgungsänderungsgesetzes
steuerverkürzungsbekämpfungsgesetz
wirkungsgleich
antiterrorismuskonvention


### 2002:
lötzsch
acrylamid
nitrofen
stammzelllinien
isaf
djerba
stokar
karzai
birgitt
kompetenzteam
neuforn
bildungsberichterstattung
riesterrente
dimethoat
beitragssatzsicherungsgesetz
hajduk
lebaycid
ostendorff
jirga
vorbehaltslösung
connemann
vermittlungsgutscheine
loya
steuervergünstigungsabbaugesetz
pinkwart
karsli
serowiecki
grygier
zinsabgeltungsteuer
nepad


### 2003:
kunduz
brunkhorst
reparaturklausel
kauch
barwertverordnung
nachhaltigkeitsfaktor
marko
collect
allokationsplan
gottesbezug
reiterstaffel
strothmann
bunia
lena
erantwortung
uribe
justizmodernisierungsgesetz
hilbrecht
kleinunternehmerförderungsgesetz
monuc
mauteinführung
konventsentwurf
gmg
anda
ehrbeauftragten
lautenschläger
digitalfunks
ituri
fallpauschalenänderungsgesetz
mautsystem


### 2004:
darfur
wissing
faizabad
reisebüroverfahren
arbeitsagenturen
elvira
althea
auernhammer
addicks
reiseschutzpass
zusatzbarbetrag
tagesbetreuungsausbaugesetz
touriste
kofler
feldbeobachtung
beslan
öpp
anreizregulierung
ackerbauverbot
zuwanderungsrat
wächterrat
arbeitsagentur
resale
juschtschenko
einsatzversorgungsgesetz
urwaldschutz
jugendfreiwilligendienste
reiseschutzpässe
zuwanderungsrates
reiseschutzpassverfahren


### 2005:
jobgipfel
lazar
kontenabruf
vollkostenfinanzierung
ramelow
vaterschaftstests
unmis
freilandeiern
finanzkraftklausel
volltextdatei
vorstandsvergütungen
bondsteel
jobgipfels
kontenabfrage
nordseeregion
optionskommunen
haradinaj
stalker
bundesnetzagentur
zollfahndungsdienstgesetzes
antiterrordatei
gammelfleisch
indexdateien
meinhardt
gasprom
energieausweis
moshammer
steuerstundungsmodellen
linksfraktion
toncar


### 2006:
hochschulpakt
hightechstrategie
normenkontrollrat
nešković
integrationsgipfel
flugticketabgabe
saisonkurzarbeitergeld
mittelstandsentlastungsgesetz
hochschulpaktes
auktionierung
kooperationsverbot
nouripour
transparenzinitiative
omid
onlinedurchsuchung
dorothée
sportwetten
sanio
grundrechteagentur
libanoneinsatz
pfos
regulierungsferien
normenkontrollrats
energiegipfels
scoring
streumunition
eckpunkteregelung
gesprächsleitfaden
terrorismusbekämpfungsergänzungsgesetz
vertragsarztrechtsänderungsgesetz


### 2007:
reformvertrag
beus
steinecke
unamid
pflegestützpunkte
eisel
herlitzius
erwerbstätigenzuschuss
ths
mügeln
postmindestlohn
direktanspruch
epas
qualifizierungsinitiative
eingliederungsbeitrag
hybridmission
betreuungsgeldes
daðdelensevim
anteilsverfahren
kommunalkombi
qualifizierungszuschuss
policenmodell
ccs
klimaschutzhaushalt
kavala
evonik
ampelkennzeichnung
kinderbetreuungsausbau
vernor
diwell


### 2008:
hdj
obama
eulex
atalanta
christival
eigenheimrentengesetz
rettungspaket
bildungsrepublik
strengmann
kinderregelsätze
sozialticket
schulbedarfspaket
filmerbe
dronabinol
schulstarterpaket
ypsilanti
pirateriebekämpfung
sozialtickets
filmerbes
messwesens
erdverkabelung
medwedew
finanzmarktstabilisierungsgesetz
rüffert
arbeitsschutzstrategie
vermittlungsbudget
viking
nahrungsmittelkrise
kifög
fdlr


### 2009:
wachstumsbeschleunigungsgesetz
umweltprämie
soffin
högl
zelaya
konjunkturpaketen
kinderpornografischen
bankenrettung
krischer
kinderpornografische
kiesewetter
breitbandstrategie
aken
kriegsverräter
arug
kriegsverrat
liebich
frieser
tören
groschek
alpers
bildungsstreik
wachstumsbeschleunigungsgesetzes
facebook
malczak
gambke
birkwald
serkan
keul
kekeritz


### 2010:
ead
bankenabgabe
bildungspaket
klamt
bundesfreiwilligendienst
finanzmarkttransaktionsteuer
krestel
mappus
referenzgruppe
cgzp
bundesarbeitsministerin
bildungsketten
vulkanasche
schottern
regelbedarfen
validierungsförderung
bildungslotsen
hofabgabeklausel
schwesig
lernförderung
kernbrennstoffsteuer
acs
svenchristian
jobcenterreform
teilhabepaket
aschtiani
netzpolitik
patientenrechtegesetz
amnog
kreditausfallversicherungen


### 2011:
fukushima
esm
ebner
nanosilber
extremismusklausel
unmiss
schuldenschnitt
kabinenluft
asylblg
versorgungsstrukturgesetz
hebelung
fracking
donaustrategie
troy
screenshots
liebigstrasse
brennelementekugeln
funkzellenabfrage
demokratieerklärung
signalton
zoni
rentendialog
oits
teilhabepaketes
demografiebericht
ausstellungszahlung
fiskalunion
digitask
mediationsgesetz
dreierbesetzung


### 2012:
fiskalpakt
fiskalvertrag
büssemaker
polheim
bankenunion
todtenhausen
hollande
entscheidungslösung
netzentwicklungsplan
hellmich
dienstleistungskonzessionen
sawade
arfst
flaminia
stöbe
managementprämie
fiskalpakts
altschuldentilgungsfonds
sahelregion
lebensleistungsrente
ied
kleinstkapitalgesellschaften
fiskalvertrags
fiskalpaktes
faktenerhebung
spartengewerkschaften
kleinstgenossenschaften
birkner
notfallsanitäter
cabos


### 2013:
redenzu
snowden
mütterrente
mietpreisbremse
afisma
kieckbusch
minusma
prism
methamphetamin
mindestpersonalbemessung
sukzessivadoption
gruppenverfahren
datenbankgrundbuch
btmvv
cookinseln
highs
gettorente
investitionspartnerschaft
fatca
substituierenden
mnla
behinderungskompensierenden
unternehmensstrafrecht
ttip
kidal
kapitalanlagegesetzbuch
prostitutionsstätten
kohleausstiegsgesetz
bushido
behinderungskompensierender


### 2014:
ceta
flisek
elterngeldplus
petry
zollner
bundesteilhabegesetz
pflegestärkungsgesetz
bmub
ebolaepidemie
prokon
chlorhühnchen
peschmerga
ausländermaut
levonorgestrel
poroschenko
netzallianz
bundesteilhabegesetzes
westermayer
groko
zukunftsvergessen
pflegevorsorgefonds
familienarbeitszeit
engelmeier
ray
tisa
cape
tarifpaket
kobane
atd
triton


### 2015:
mistura
ronja
thissen
staffan
sousse
badawi
unmil
finanzzufluss
krankenhausstrukturgesetz
aufarbeitungskommission
selektoren
iarc
syrienkrieges
handelsgerichtshof
raif
eunavfor
mikroplastik
ryglewski
althengstett
mosblech
aiib
elfi
tarifeinheitsgesetz
palliativgesetz
höchstspeicherfrist
varoufakis
hebdo
selektorenliste
piatto
pflegestellenförderprogramm


### 2016:
brexit
böhmermann
incirlik
strommarktgesetz
cosse
ripsam
umgangsmehrbedarf
gewinnglättung
idomeni
integrationspauschale
wasserpfeifen
aleppos
finanzmarktnovellierungsgesetz
ankunftsnachweis
sektorkopplung
freeland
awstg
grapschen
strategierahmen
cis
flüchtlingsdeal
braunsbach
klimaschutzplanes
primark
psychvvg
integrationspaket
airdrops
behindertengleichstellungsrechts
kulturgutschutzes
bthg


### 2017:
amri
pesco
netzwerkdurchsetzungsgesetz
weidel
theurer
paradise
sitta
netzdg
nicola
mieterstromgesetz
stoffstrombilanz
entgelttransparenzgesetz
protschka
otten
traditionsschifffahrt
ehrhorn
hebner
corbyn
curio
brennelementelieferungen
polat
dienstleistungskarte
helin
masi
cotar
keuter
kaeser
eleonora
nastic
schmidtke


### 2018:
brückenteilzeit
migrationspakt
hardwarenachrüstung
esport
wechselmodell
wohngipfel
insektenschutz
hardwarenachrüstungen
serviceopposition
kohlekommission
ackerbaustrategie
qualifizierungschancengesetz
hänel
wohnraumoffensive
rentenpakt
digitalfonds
adrs
digitalsteuer
dieselfahrverbote
letztsicherung
teilhabechancengesetz
versichertenentlastungsgesetz
wohnungsgipfel
heimatministerium
meuthen
experimentierräume
dieselbesitzer
fachkräfteeinwanderungsgesetz
rugy
dieselbusse


### 2019:
uploadfilter
lübcke
univ
kyiv
fridays
nezahat
baradari
nordmazedonien
zickenheiner
elektrokleinstfahrzeuge
clankriminalität
miri
heidt
guaidó
uploadfiltern
afdfraktion
klimanotstand
strukturstärkungsgesetz
selenskyj
thunberg
assange
klimakabinetts
elektrokleinstfahrzeugen
wohnsitzregelung
pd
bonpflicht
amtszeitbegrenzung
lieferkettengesetz
nordostsyrien
oah


### 2020:
coronakrise
coronapandemie
lockdown
coronamassnahmen
coronazeiten
maskenpflicht
lockdowns
coronahilfen
coronazeit
irini
wirtschaftsstabilisierungsfonds
arbeitsschutzkontrollgesetz
nölke
coronabedingt
afkari
biontech
rentenübersicht
novemberhilfe
coronasituation
coronabedingten
curevac
tichanowskaja
coronapolitik
coronabedingte
novemberhilfen
teststrategie
pspp
pandemiezeiten
krankenhauszukunftsgesetz
testkapazitäten


### 2021:
selbsttests
bundesnotbremse
nordt
impfangebot
maika
gohl
verimpft
impfstoffbeschaffung
eigentests
mindestkurzarbeitergeld
teilhabestärkungsgesetz
osterruhe
virusvarianten
virusmutationen
maskendeals
wertpapierinstitute
betriebsrätemodernisierungsgesetz
sormas
löschmoratorium
impfportal
insektenschutzpaket
impffortschritt
datenkompetenz
barrierefreiheitsstärkungsgesetz
pflegeanwendungen
warp
bauwende
impftermin
coronaimpfpass
fondsstandortgesetz