---
title: "Zurück in die Zukunft"
---

Notizen und Referenzen zum Vortrag 'Zurück in die Zukunft. Die Vermessung der Vergangenheit'
### VHS Borken Semestereröffnung, 18. September 2025

---

### Vitaminen / Eviunis

Huijnen, Pim, [‘Het wondermiddel van professor Buytendijk’](https://platform.openjournals.nl/studium/article/view/20214), Studium 4 (2010) 155-169.

Scheunert, A., Schieblich, M. & Reschke, J. ['Über den Vitamingehalt von Eviunis (Vitophos)'](https://rdcu.be/eGOFh). Zeitschr. f. Untersuchung der Lebensmittel 66, 271–278 (1933). https://doi.org/10.1007/BF01664670.

Werbung De Betuwe jams, Nieuwe Rotterdamsche Courant, 20.09.1929, S. 20. Delpher: [https://resolver.kb.nl/resolve?urn=ddd:010030488:mpeg21:p020](https://resolver.kb.nl/resolve?urn=ddd:010030488:mpeg21:p020).

Werbung Kwatta Ma-vie chocolade, Twentsch Dagblad Tubantia en Enschedese Courant, 01.03.1929, S. 6. Delpher: [https://resolver.kb.nl/resolve?urn=MMSAEN01:000049959:mpeg21:p006(https://resolver.kb.nl/resolve?urn=MMSAEN01:000049959:mpeg21:p006).

Werbung Ranja en Rojo, Nieuwe Rotterdamsche Courant, 13.09.1929, S. 15. Delpher: [https://resolver.kb.nl/resolve?urn=ddd:010030476:mpeg21:p015(https://resolver.kb.nl/resolve?urn=ddd:010030476:mpeg21:p015).

Werbung Vitawin, Nieuwe Rotterdamsche Courant, 16.11.1929, S. 1. Delpher: [https://resolver.kb.nl/resolve?urn=ddd:010030585:mpeg21:p001](https://resolver.kb.nl/resolve?urn=ddd:010030585:mpeg21:p001.

[Werbung 'Beter Wittebrood'](http://historisch.groene.nl/nummer/1930-11-15/pagina/12), De Groene Amsterdammer, 15.11.1930, S. 12.

Suchfrage ['vitamin*'](https://www.delpher.nl/nl/kranten/results?query=vitamin*&coll=ddd) in Delpher Zeitungsarchiv.

Suchfrage ['vitamin*'](https://www.deutsche-digitale-bibliothek.de/search/newspaper?query=vitamin*) im deutschen Zeitungsportal.

### Bundestag

Lange, Kai-Robin and Jentsch, Carsten, ['SpeakGer: A meta-data enriched speech corpus of German state and federal parliaments'](https://berd-platform.de/records/g3225-rba63), Proceedings of the 3rd Workshop on Computational Linguistics for Political Text Analysis @ KONVENS (2023). 

G.H. Brundtland et.al., [Our Common Future. Report of the World Commission on Environment and Development](https://www.brundtland.co.za/other-publication/brundtland-report-1987-our-common-future/) (1987)

[Neue Wörter pro Jahr im Bundestag, 1950-2021](new_words_per_year.html)

Karen Zhou, Alexander A Meitus, Milo Chase, Grace Wang, Anne Mykland, William Howell, Chenhao Tan, ['Quantifying the uniqueness and divisiveness of presidential discourse'](https://doi.org/10.1093/pnasnexus/pgae431), PNAS Nexus, Volume 3, Issue 10, October (2024), pp. 43.

Pim Huijnen, [‘Everyday memory: a computational analysis of the changing relation between past and present in Dutch newspapers in the twentieth century’](https://doi.org/10.1093/llc/fqad099), Digital Scholarship in the Humanities 00 (2024), pp. 1–12.

### Word Embeddings

Tomas Mikolov, Wen-tau Yih, and Geoffrey Zweig, ['Linguistic Regularities in Continuous Space Word Representations'](https://aclanthology.org/N13-1090/). In Proceedings of the 2013 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies (2013), pp. 746–751, Atlanta, Georgia.

### Generative KI

Werbung N.V. Nederlandse Gasunie, Trouw, 04.06.1968, P. 2. Delpher: [https://resolver.kb.nl/resolve?urn=ABCDDD:010814088:mpeg21:a0012](https://resolver.kb.nl/resolve?urn=ABCDDD:010814088:mpeg21:a0012)

Sentimentanalyse niederländisches Zeitungsdiskurs über Energie: [Histaware Projekt](https://digitalhistory.hum.uu.nl/projects/35-histaware-mining-historical-trajectories-of-awareness) (2020-2021) und [INTEREST Projekt](https://digitalhistory.hum.uu.nl/projects/46-interest-mining-historical-newspapers-for-sentiments-over-time) (2024-2025)

### Schluss

Kiran Tomlinson et.al., [‘Working with AI: Measuring the Occupational Implications of Generative AI’](https://doi.org/10.48550/arXiv.2507.07935) (2025), arXiv: 2507.07935.

Foto 'Kinder mit Rachitis', [Wellcome Collection M0003399EB](https://wellcomecollection.org/works/t3rrbtsm).

Vitanova-Lebertran Werbung im Hamburger Fremdenblatt, Abendausgabe, 27.05.1927, S. 10. Deutsches Zeitungsportal: [https://www.deutsche-digitale-bibliothek.de/newspaper/item/H2CD54KS5HKLWWDZGMEMDDEYG5BUQJVE?issuepage=10](https://www.deutsche-digitale-bibliothek.de/newspaper/item/H2CD54KS5HKLWWDZGMEMDDEYG5BUQJVE?issuepage=10).

'Steenkool: een goed alternatief', Nederlands Dagblad, 02.02.1978, S. 7. Delpher: [https://resolver.kb.nl/resolve?urn=ddd:010682195:mpeg21:a0095](https://resolver.kb.nl/resolve?urn=ddd:010682195:mpeg21:a0095).

'Steenkool - energiebron met tal van toepassingsmogelijkheden', De Waarheid, 29.08.1979, S. 8. Delpher: [https://resolver.kb.nl/resolve?urn=ddd:010377551:mpeg21:a0144](https://resolver.kb.nl/resolve?urn=ddd:010377551:mpeg21:a0144).

Shojaee, Parshin, Iman Mirzadeh, Keivan Alizadeh, Maxwell Horton, Samy Bengio, and Mehrdad Farajtabar, 'The Illusion of Thinking: Understanding the Strengths and Limitations of Reasoning Models via the Lens of Problem Complexity', (2025) [arXiv:2506.09250v2](https://arxiv.org/abs/2506.09250v2) [cs.AI].

Clark, Christopher M. The Sleepwalkers: How Europe Went to War in 1914 (New York: Harper, 2013).

